//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Attribute.
        /// </summary>
        internal static string AddNewAttributeHeader {
            get {
                return ResourceManager.GetString("AddNewAttributeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Name.
        /// </summary>
        internal static string AttributeName {
            get {
                return ResourceManager.GetString("AttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string btnTest {
            get {
                return ResourceManager.GetString("btnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Connection.
        /// </summary>
        internal static string ConnectorAddnew {
            get {
                return ResourceManager.GetString("ConnectorAddnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All existing connection.
        /// </summary>
        internal static string ConnectorAllExistingConnection {
            get {
                return ResourceManager.GetString("ConnectorAllExistingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Connection.
        /// </summary>
        internal static string ConnectorApiPageHeading {
            get {
                return ResourceManager.GetString("ConnectorApiPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string ConnectorDatabase {
            get {
                return ResourceManager.GetString("ConnectorDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string ConnectorDatabaseName {
            get {
                return ResourceManager.GetString("ConnectorDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection.
        /// </summary>
        internal static string ConnectorDatabasePageHeading {
            get {
                return ResourceManager.GetString("ConnectorDatabasePageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Connection.
        /// </summary>
        internal static string ConnectorExisting {
            get {
                return ResourceManager.GetString("ConnectorExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ftp.
        /// </summary>
        internal static string ConnectorFTP {
            get {
                return ResourceManager.GetString("ConnectorFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Folder.
        /// </summary>
        internal static string ConnectorFTPDefaultFolder {
            get {
                return ResourceManager.GetString("ConnectorFTPDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode (Active or Passive).
        /// </summary>
        internal static string ConnectorFTPMode {
            get {
                return ResourceManager.GetString("ConnectorFTPMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Connection.
        /// </summary>
        internal static string ConnectorFTPPageHeading {
            get {
                return ResourceManager.GetString("ConnectorFTPPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Manager.
        /// </summary>
        internal static string ConnectorHeading {
            get {
                return ResourceManager.GetString("ConnectorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Name.
        /// </summary>
        internal static string ConnectorName {
            get {
                return ResourceManager.GetString("ConnectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exisiting connection.
        /// </summary>
        internal static string ConnectorNoExistingConnection {
            get {
                return ResourceManager.GetString("ConnectorNoExistingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Password.
        /// </summary>
        internal static string ConnectorPassword {
            get {
                return ResourceManager.GetString("ConnectorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Default Path.
        /// </summary>
        internal static string ConnectorPath {
            get {
                return ResourceManager.GetString("ConnectorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number.
        /// </summary>
        internal static string ConnectorPort {
            get {
                return ResourceManager.GetString("ConnectorPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        internal static string ConnectorPrivateKey {
            get {
                return ResourceManager.GetString("ConnectorPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        internal static string ConnectorSaveMessage {
            get {
                return ResourceManager.GetString("ConnectorSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Key.
        /// </summary>
        internal static string ConnectorSecret {
            get {
                return ResourceManager.GetString("ConnectorSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server/IP.
        /// </summary>
        internal static string ConnectorServer {
            get {
                return ResourceManager.GetString("ConnectorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string ConnectorTest {
            get {
                return ResourceManager.GetString("ConnectorTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test successfully.
        /// </summary>
        internal static string ConnectorTestMessage {
            get {
                return ResourceManager.GetString("ConnectorTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Username.
        /// </summary>
        internal static string ConnectorUserName {
            get {
                return ResourceManager.GetString("ConnectorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed.
        /// </summary>
        internal static string ConnectorValidationFailed {
            get {
                return ResourceManager.GetString("ConnectorValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Step 1.
        /// </summary>
        internal static string DiscoveryButtonBack1 {
            get {
                return ResourceManager.GetString("DiscoveryButtonBack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Step 2.
        /// </summary>
        internal static string DiscoveryButtonBack2 {
            get {
                return ResourceManager.GetString("DiscoveryButtonBack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step 2.
        /// </summary>
        internal static string DiscoveryButtonStep2 {
            get {
                return ResourceManager.GetString("DiscoveryButtonStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step 3.
        /// </summary>
        internal static string DiscoveryButtonStep3 {
            get {
                return ResourceManager.GetString("DiscoveryButtonStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery of points.
        /// </summary>
        internal static string DiscoveryHeading {
            get {
                return ResourceManager.GetString("DiscoveryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step1. Un-Structure.
        /// </summary>
        internal static string DiscoveryHeadingStep1 {
            get {
                return ResourceManager.GetString("DiscoveryHeadingStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step2. Tags.
        /// </summary>
        internal static string DiscoveryHeadingStep2 {
            get {
                return ResourceManager.GetString("DiscoveryHeadingStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step3. Structure.
        /// </summary>
        internal static string DiscoveryHeadingStep3 {
            get {
                return ResourceManager.GetString("DiscoveryHeadingStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover New Point.
        /// </summary>
        internal static string DiscoveryNewPoint {
            get {
                return ResourceManager.GetString("DiscoveryNewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, processing your request .........
        /// </summary>
        internal static string DiscoveryPleaseWait {
            get {
                return ResourceManager.GetString("DiscoveryPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom hierarchy.
        /// </summary>
        internal static string DiscoveryStep3Custom {
            get {
                return ResourceManager.GetString("DiscoveryStep3Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default hierarchy.
        /// </summary>
        internal static string DiscoveryStep3Default {
            get {
                return ResourceManager.GetString("DiscoveryStep3Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innon Analytics.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait..........
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
    }
}
