//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.DataWareHouseService.DatawareHouseEntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InnonAnalyticsWarehouseEntities : DbContext, IInnonAnalyticsWarehouseEntities
    {
        public InnonAnalyticsWarehouseEntities()
            : base("name=InnonAnalyticsWarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Date_Dim> Date_Dim { get; set; }
        public virtual DbSet<Point_Agg_Year> Point_Agg_Year { get; set; }
        public virtual DbSet<Point_Agg_Day> Point_Agg_Day { get; set; }
        public virtual DbSet<Point_Agg_Hour> Point_Agg_Hour { get; set; }
        public virtual DbSet<Point_Agg_Month> Point_Agg_Month { get; set; }
        public virtual DbSet<Point_Agg_Week> Point_Agg_Week { get; set; }
        public virtual DbSet<Point_Dim> Point_Dim { get; set; }
        public virtual DbSet<Point_Measure_Fact> Point_Measure_Fact { get; set; }
        public virtual DbSet<FactsRestatementAudit> FactsRestatementAudits { get; set; }
    }
}
