//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.DataWareHouseService.DatawareHouseEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date_Dim
    {
        public System.DateTime Date_ID { get; set; }
        public int Week_ID { get; set; }
        public int Month_ID { get; set; }
        public int Quarter_ID { get; set; }
        public int Year_ID { get; set; }
    }
}
