//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.DataWareHouseService.DatawareHouseEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactsRestatementAudit
    {
        public long ID { get; set; }
        public long Point_ID { get; set; }
        public System.DateTime Timestamp_From { get; set; }
        public System.DateTime Timestamp_To { get; set; }
        public double Old_Value { get; set; }
        public double New_Value { get; set; }
        public bool Send_To_DW { get; set; }
        public System.DateTime Updated_Datetime { get; set; }
        public long Updated_User_ID { get; set; }
    }
}
