//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.DataWareHouseService.DatawareHouseEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point_Dim
    {
        public long Point_ID { get; set; }
        public long Equipment_ID { get; set; }
        public long Site_ID { get; set; }
        public long Client_ID { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Department { get; set; }
        public string Zone { get; set; }
        public string Floor { get; set; }
        public string Custom_Tag_1 { get; set; }
        public string Custom_Tag_2 { get; set; }
        public string Custom_Tag_3 { get; set; }
        public string Custom_Tag_4 { get; set; }
        public string Custom_Tag_5 { get; set; }
        public string Custom_Tag_6 { get; set; }
        public string Custom_Tag_7 { get; set; }
        public string Custom_Tag_8 { get; set; }
        public string Custom_Tag_9 { get; set; }
        public string Custom_Tag_10 { get; set; }
        public string Point { get; set; }
    }
}
