//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.DataWareHouseService.DatawareHouseEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point_Measure_Fact
    {
        public int ID { get; set; }
        public System.DateTime Date_ID { get; set; }
        public long Client_ID { get; set; }
        public long Point_ID { get; set; }
        public System.DateTime Timestamp_From { get; set; }
        public System.DateTime Timestamp_To { get; set; }
        public System.DateTime Hour_ID { get; set; }
        public string Unit_Of_Measurement { get; set; }
        public Nullable<double> Min_Value { get; set; }
        public Nullable<double> Max_Value { get; set; }
        public Nullable<long> DataRecordingFrequency { get; set; }
        public Nullable<int> Schedule_ID { get; set; }
        public double Value { get; set; }
        public double Raw_Value { get; set; }
        public System.DateTime Last_Update_Time { get; set; }
        public string External_ID { get; set; }
        public string Point_Status { get; set; }
    }
}
