//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Attribute.
        /// </summary>
        internal static string AddNewAttributeHeader {
            get {
                return ResourceManager.GetString("AddNewAttributeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Name.
        /// </summary>
        internal static string AttributeName {
            get {
                return ResourceManager.GetString("AttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string Audit_Heading {
            get {
                return ResourceManager.GetString("Audit_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string BarChart_Title {
            get {
                return ResourceManager.GetString("BarChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string btnTest {
            get {
                return ResourceManager.GetString("btnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Type.
        /// </summary>
        internal static string Chart_Type {
            get {
                return ResourceManager.GetString("Chart_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Metric.
        /// </summary>
        internal static string Choose_Metric {
            get {
                return ResourceManager.GetString("Choose_Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Widget.
        /// </summary>
        internal static string Choose_Widget {
            get {
                return ResourceManager.GetString("Choose_Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ConnectorActive {
            get {
                return ResourceManager.GetString("ConnectorActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Connection.
        /// </summary>
        internal static string ConnectorAddnew {
            get {
                return ResourceManager.GetString("ConnectorAddnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All existing connection.
        /// </summary>
        internal static string ConnectorAllExistingConnection {
            get {
                return ResourceManager.GetString("ConnectorAllExistingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        internal static string ConnectorAPI {
            get {
                return ResourceManager.GetString("ConnectorAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Connection.
        /// </summary>
        internal static string ConnectorApiPageHeading {
            get {
                return ResourceManager.GetString("ConnectorApiPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string ConnectorDatabase {
            get {
                return ResourceManager.GetString("ConnectorDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string ConnectorDatabaseName {
            get {
                return ResourceManager.GetString("ConnectorDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection.
        /// </summary>
        internal static string ConnectorDatabasePageHeading {
            get {
                return ResourceManager.GetString("ConnectorDatabasePageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Connection.
        /// </summary>
        internal static string ConnectorExisting {
            get {
                return ResourceManager.GetString("ConnectorExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ftp.
        /// </summary>
        internal static string ConnectorFTP {
            get {
                return ResourceManager.GetString("ConnectorFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Folder.
        /// </summary>
        internal static string ConnectorFTPDefaultFolder {
            get {
                return ResourceManager.GetString("ConnectorFTPDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode (Active or Passive).
        /// </summary>
        internal static string ConnectorFTPMode {
            get {
                return ResourceManager.GetString("ConnectorFTPMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Connection.
        /// </summary>
        internal static string ConnectorFTPPageHeading {
            get {
                return ResourceManager.GetString("ConnectorFTPPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Manager.
        /// </summary>
        internal static string ConnectorHeading {
            get {
                return ResourceManager.GetString("ConnectorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Name.
        /// </summary>
        internal static string ConnectorName {
            get {
                return ResourceManager.GetString("ConnectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exisiting connection.
        /// </summary>
        internal static string ConnectorNoExistingConnection {
            get {
                return ResourceManager.GetString("ConnectorNoExistingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Password.
        /// </summary>
        internal static string ConnectorPassword {
            get {
                return ResourceManager.GetString("ConnectorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Default Path.
        /// </summary>
        internal static string ConnectorPath {
            get {
                return ResourceManager.GetString("ConnectorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number.
        /// </summary>
        internal static string ConnectorPort {
            get {
                return ResourceManager.GetString("ConnectorPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        internal static string ConnectorPrivateKey {
            get {
                return ResourceManager.GetString("ConnectorPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        internal static string ConnectorSaveMessage {
            get {
                return ResourceManager.GetString("ConnectorSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Key.
        /// </summary>
        internal static string ConnectorSecret {
            get {
                return ResourceManager.GetString("ConnectorSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server/IP.
        /// </summary>
        internal static string ConnectorServer {
            get {
                return ResourceManager.GetString("ConnectorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string ConnectorTest {
            get {
                return ResourceManager.GetString("ConnectorTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test successfully.
        /// </summary>
        internal static string ConnectorTestMessage {
            get {
                return ResourceManager.GetString("ConnectorTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Type.
        /// </summary>
        internal static string ConnectorType {
            get {
                return ResourceManager.GetString("ConnectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Username.
        /// </summary>
        internal static string ConnectorUserName {
            get {
                return ResourceManager.GetString("ConnectorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed.
        /// </summary>
        internal static string ConnectorValidationFailed {
            get {
                return ResourceManager.GetString("ConnectorValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashBoardHeading {
            get {
                return ResourceManager.GetString("DashBoardHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Step 1.
        /// </summary>
        internal static string DiscoveryButtonBack1 {
            get {
                return ResourceManager.GetString("DiscoveryButtonBack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Step 2.
        /// </summary>
        internal static string DiscoveryButtonBack2 {
            get {
                return ResourceManager.GetString("DiscoveryButtonBack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step 2.
        /// </summary>
        internal static string DiscoveryButtonStep2 {
            get {
                return ResourceManager.GetString("DiscoveryButtonStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step 3.
        /// </summary>
        internal static string DiscoveryButtonStep3 {
            get {
                return ResourceManager.GetString("DiscoveryButtonStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery of points.
        /// </summary>
        internal static string DiscoveryHeading {
            get {
                return ResourceManager.GetString("DiscoveryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step1. Un-Structure.
        /// </summary>
        internal static string DiscoveryHeadingStep1 {
            get {
                return ResourceManager.GetString("DiscoveryHeadingStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step2. Tags.
        /// </summary>
        internal static string DiscoveryHeadingStep2 {
            get {
                return ResourceManager.GetString("DiscoveryHeadingStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step3. Structure.
        /// </summary>
        internal static string DiscoveryHeadingStep3 {
            get {
                return ResourceManager.GetString("DiscoveryHeadingStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover New Point.
        /// </summary>
        internal static string DiscoveryNewPoint {
            get {
                return ResourceManager.GetString("DiscoveryNewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, processing your request .........
        /// </summary>
        internal static string DiscoveryPleaseWait {
            get {
                return ResourceManager.GetString("DiscoveryPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom hierarchy.
        /// </summary>
        internal static string DiscoveryStep3Custom {
            get {
                return ResourceManager.GetString("DiscoveryStep3Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default hierarchy.
        /// </summary>
        internal static string DiscoveryStep3Default {
            get {
                return ResourceManager.GetString("DiscoveryStep3Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string DonutChart_Title {
            get {
                return ResourceManager.GetString("DonutChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Chart Type.
        /// </summary>
        internal static string DropDownChartTypeSelect {
            get {
                return ResourceManager.GetString("DropDownChartTypeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Connection Type.
        /// </summary>
        internal static string DropDownConnectorSelect {
            get {
                return ResourceManager.GetString("DropDownConnectorSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dashboard Type.
        /// </summary>
        internal static string DropDownDashboardSelect {
            get {
                return ResourceManager.GetString("DropDownDashboardSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FTP Mode.
        /// </summary>
        internal static string DropDownFTPModeSelect {
            get {
                return ResourceManager.GetString("DropDownFTPModeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gateway Type.
        /// </summary>
        internal static string DropDownGatewaySelect {
            get {
                return ResourceManager.GetString("DropDownGatewaySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the metric.
        /// </summary>
        internal static string DropDownListMetricSelect {
            get {
                return ResourceManager.GetString("DropDownListMetricSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Time Line.
        /// </summary>
        internal static string DropDownTimeLineSelect {
            get {
                return ResourceManager.GetString("DropDownTimeLineSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipment.
        /// </summary>
        internal static string equip {
            get {
                return ResourceManager.GetString("equip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string Forgotyourpassword {
            get {
                return ResourceManager.GetString("Forgotyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GatewayType.
        /// </summary>
        internal static string GatewayType {
            get {
                return ResourceManager.GetString("GatewayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Angle.
        /// </summary>
        internal static string Gauge_End_Angle {
            get {
                return ResourceManager.GetString("Gauge_End_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value.
        /// </summary>
        internal static string Gauge_Max_Value {
            get {
                return ResourceManager.GetString("Gauge_Max_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Lable.
        /// </summary>
        internal static string Gauge_Metric_Label {
            get {
                return ResourceManager.GetString("Gauge_Metric_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Label.
        /// </summary>
        internal static string Gauge_Metric_Target_Label {
            get {
                return ResourceManager.GetString("Gauge_Metric_Target_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Unit.
        /// </summary>
        internal static string Gauge_Minor_Unit {
            get {
                return ResourceManager.GetString("Gauge_Minor_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value.
        /// </summary>
        internal static string Gauge_Min_Value {
            get {
                return ResourceManager.GetString("Gauge_Min_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Angle.
        /// </summary>
        internal static string Gauge_Start_Angle {
            get {
                return ResourceManager.GetString("Gauge_Start_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string HeatMap_Title {
            get {
                return ResourceManager.GetString("HeatMap_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innon Analytics.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legends.
        /// </summary>
        internal static string legends {
            get {
                return ResourceManager.GetString("legends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Line_Title {
            get {
                return ResourceManager.GetString("Line_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Points.
        /// </summary>
        internal static string LivePoint_Heading {
            get {
                return ResourceManager.GetString("LivePoint_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message_Box_Heading {
            get {
                return ResourceManager.GetString("Message_Box_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new metric.
        /// </summary>
        internal static string Metric_Add_New_Metric {
            get {
                return ResourceManager.GetString("Metric_Add_New_Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        internal static string Metric_Filter_By {
            get {
                return ResourceManager.GetString("Metric_Filter_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Option.
        /// </summary>
        internal static string Metric_Filter_By_Option {
            get {
                return ResourceManager.GetString("Metric_Filter_By_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter By Option.
        /// </summary>
        internal static string Metric_Filter_By_Option_Select {
            get {
                return ResourceManager.GetString("Metric_Filter_By_Option_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter By.
        /// </summary>
        internal static string Metric_Filter_By_Select {
            get {
                return ResourceManager.GetString("Metric_Filter_By_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Text.
        /// </summary>
        internal static string Metric_Filter_Text {
            get {
                return ResourceManager.GetString("Metric_Filter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By.
        /// </summary>
        internal static string Metric_Group_By {
            get {
                return ResourceManager.GetString("Metric_Group_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group By.
        /// </summary>
        internal static string Metric_Group_By_Select {
            get {
                return ResourceManager.GetString("Metric_Group_By_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Name.
        /// </summary>
        internal static string Metric_Name {
            get {
                return ResourceManager.GetString("Metric_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll up.
        /// </summary>
        internal static string Metric_Roll_Up_Function {
            get {
                return ResourceManager.GetString("Metric_Roll_Up_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        internal static string Metric_Title {
            get {
                return ResourceManager.GetString("Metric_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Type.
        /// </summary>
        internal static string Metric_Type {
            get {
                return ResourceManager.GetString("Metric_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Metric Type:- Two kind of metric type&lt;/h4&gt;&lt;p&gt;&lt;ol&gt;&lt;li&gt;System define metric (Those metrics which created from the system on the bases of tagging in the Point Tagging section)&lt;/li&gt;&lt;li&gt;User define metric (Those metrics which created by the user, Creat a new metric by using the top button &quot;Add new metric&quot;)&lt;/li&gt;&lt;/ol&gt;&lt;/p&gt;.
        /// </summary>
        internal static string Metric_Type_Note {
            get {
                return ResourceManager.GetString("Metric_Type_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Metric_Unit {
            get {
                return ResourceManager.GetString("Metric_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Metric Unit.
        /// </summary>
        internal static string Metric_Unit_Select {
            get {
                return ResourceManager.GetString("Metric_Unit_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes_Heading {
            get {
                return ResourceManager.GetString("Notes_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Parent Dashboard.
        /// </summary>
        internal static string Parent_Dashboard_Select {
            get {
                return ResourceManager.GetString("Parent_Dashboard_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string PieChart_Title {
            get {
                return ResourceManager.GetString("PieChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select point.
        /// </summary>
        internal static string PleaseSelectPoint {
            get {
                return ResourceManager.GetString("PleaseSelectPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Roll Up.
        /// </summary>
        internal static string PleaseSelectRollUp {
            get {
                return ResourceManager.GetString("PleaseSelectRollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait..........
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point.
        /// </summary>
        internal static string point {
            get {
                return ResourceManager.GetString("point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point/Element Data Access.
        /// </summary>
        internal static string PointElementDataAdmin {
            get {
                return ResourceManager.GetString("PointElementDataAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string PointMeaningFullDataDataType {
            get {
                return ResourceManager.GetString("PointMeaningFullDataDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq.
        /// </summary>
        internal static string PointMeaningFullDataFreq {
            get {
                return ResourceManager.GetString("PointMeaningFullDataFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string PointMeaningFullDataIsRead_Only {
            get {
                return ResourceManager.GetString("PointMeaningFullDataIsRead_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string PointMeaningFullDataMax {
            get {
                return ResourceManager.GetString("PointMeaningFullDataMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string PointMeaningFullDataMin {
            get {
                return ResourceManager.GetString("PointMeaningFullDataMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Tag.
        /// </summary>
        internal static string PointMeaningFullDataPointDefaultTagType {
            get {
                return ResourceManager.GetString("PointMeaningFullDataPointDefaultTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string PointMeaningFullDataPointName {
            get {
                return ResourceManager.GetString("PointMeaningFullDataPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Freq.
        /// </summary>
        internal static string PointMeaningFullDataRecordedFreq {
            get {
                return ResourceManager.GetString("PointMeaningFullDataRecordedFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string PointMeaningFullDataTags {
            get {
                return ResourceManager.GetString("PointMeaningFullDataTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string PointMeaningFullDataUnit {
            get {
                return ResourceManager.GetString("PointMeaningFullDataUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Metric.
        /// </summary>
        internal static string Point_Metric_Heading {
            get {
                return ResourceManager.GetString("Point_Metric_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Precision.
        /// </summary>
        internal static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        internal static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign me in.
        /// </summary>
        internal static string SignMeIn {
            get {
                return ResourceManager.GetString("SignMeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site.
        /// </summary>
        internal static string site {
            get {
                return ResourceManager.GetString("site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Stacked_Title {
            get {
                return ResourceManager.GetString("Stacked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Line.
        /// </summary>
        internal static string Time_Line {
            get {
                return ResourceManager.GetString("Time_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Tree_Map_Title {
            get {
                return ResourceManager.GetString("Tree_Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this widget?.
        /// </summary>
        internal static string WidgetDeleteMes {
            get {
                return ResourceManager.GetString("WidgetDeleteMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Widget_Add_Edit_Finished {
            get {
                return ResourceManager.GetString("Widget_Add_Edit_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        internal static string Widget_Add_Edit_Metric {
            get {
                return ResourceManager.GetString("Widget_Add_Edit_Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with (Target).
        /// </summary>
        internal static string Widget_Add_Edit_Metric_Target {
            get {
                return ResourceManager.GetString("Widget_Add_Edit_Metric_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Metric.
        /// </summary>
        internal static string Widget_Add_Edit_Target_Metric {
            get {
                return ResourceManager.GetString("Widget_Add_Edit_Target_Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add widget done successfully.
        /// </summary>
        internal static string Widget_Add_Success {
            get {
                return ResourceManager.GetString("Widget_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update widget done successfully.
        /// </summary>
        internal static string Widget_Edit_Success {
            get {
                return ResourceManager.GetString("Widget_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget Title.
        /// </summary>
        internal static string Widget_Title {
            get {
                return ResourceManager.GetString("Widget_Title", resourceCulture);
            }
        }
    }
}
