//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Company1 = new HashSet<Company>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Postcode { get; set; }
        public string ContactNumber { get; set; }
        public bool Disable { get; set; }
        public Nullable<int> ParentID { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public string City { get; set; }
        public int CountryID_FK { get; set; }
        public string ProfilePic { get; set; }
        public string ColorScheme { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
    
        public virtual ICollection<Company> Company1 { get; set; }
        public virtual Company Company2 { get; set; }
        public virtual Country Country { get; set; }
    }
}
