//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public int ID { get; set; }
        public string CountryName { get; set; }
        public bool Disabled { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
    }
}
