//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSourceType
    {
        public DataSourceType()
        {
            this.DataSourceElements = new HashSet<DataSourceElement>();
        }
    
        public int ID { get; set; }
        public string SourceType { get; set; }
    
        public virtual ICollection<DataSourceElement> DataSourceElements { get; set; }
    }
}
