//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSourceElement
    {
        public int ID { get; set; }
        public int DataSourceTypeID_FK { get; set; }
        public int ElementTypeID_FK { get; set; }
        public string ConnectionString { get; set; }
    
        public virtual DataSourceType DataSourceType { get; set; }
        public virtual Element Element { get; set; }
    }
}
