//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBLog
    {
        public int ID { get; set; }
        public int UserID_FK { get; set; }
        public string TableName { get; set; }
        public int RowID { get; set; }
        public string Description { get; set; }
        public string Message { get; set; }
        public string LogLevel { get; set; }
        public System.DateTime DateofEntry { get; set; }
    }
}
