//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public Description()
        {
            this.AttributeTypes = new HashSet<AttributeType>();
            this.Elements = new HashSet<Element>();
            this.ElementTypes = new HashSet<ElementType>();
            this.LanguageDescriptions = new HashSet<LanguageDescription>();
            this.Menus = new HashSet<Menu>();
            this.SelectionTypes = new HashSet<SelectionType>();
        }
    
        public int ID { get; set; }
    
        public virtual ICollection<AttributeType> AttributeTypes { get; set; }
        public virtual ICollection<Element> Elements { get; set; }
        public virtual ICollection<ElementType> ElementTypes { get; set; }
        public virtual ICollection<LanguageDescription> LanguageDescriptions { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<SelectionType> SelectionTypes { get; set; }
    }
}
