//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public Element()
        {
            this.DataSourceElements = new HashSet<DataSourceElement>();
        }
    
        public int ID { get; set; }
        public int DescriptionID_FK { get; set; }
        public int ElementTypeID_FK { get; set; }
        public int ParentID_FK { get; set; }
        public bool Disabled { get; set; }
        public string ExternalUniqueRef { get; set; }
    
        public virtual ICollection<DataSourceElement> DataSourceElements { get; set; }
        public virtual Description Description { get; set; }
        public virtual ElementType ElementType { get; set; }
    }
}
