//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.LanguageDescriptions = new HashSet<LanguageDescription>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string CultureValue { get; set; }
        public bool Disabled { get; set; }
    
        public virtual ICollection<LanguageDescription> LanguageDescriptions { get; set; }
    }
}
