//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectionTypeValue
    {
        public SelectionTypeValue()
        {
            this.Formulae = new HashSet<Formula>();
            this.FormulaItems = new HashSet<FormulaItem>();
            this.ScheduleHours = new HashSet<ScheduleHour>();
        }
    
        public int ID { get; set; }
        public int SelectionTypeID_FK { get; set; }
        public string SelectionValue { get; set; }
        public string SelectionText { get; set; }
    
        public virtual ICollection<Formula> Formulae { get; set; }
        public virtual ICollection<FormulaItem> FormulaItems { get; set; }
        public virtual ICollection<ScheduleHour> ScheduleHours { get; set; }
        public virtual SelectionType SelectionType { get; set; }
    }
}
