//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChart_Metric
    {
        public int Id { get; set; }
        public Nullable<int> Pie_Chart_Id { get; set; }
        public int Metric_Id { get; set; }
        public Nullable<int> Stacked_Chart_Id { get; set; }
        public Nullable<int> Donut_Chart_Id { get; set; }
        public Nullable<int> Line_Chart_Id { get; set; }
    
        public virtual tblChart_Donut tblChart_Donut { get; set; }
        public virtual tblChart_Pie tblChart_Pie { get; set; }
        public virtual tblChart_Stacked tblChart_Stacked { get; set; }
        public virtual tblMetric tblMetric { get; set; }
        public virtual tblChart_Line tblChart_Line { get; set; }
    }
}
