//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConnector
    {
        public tblConnector()
        {
            this.tblElements = new HashSet<tblElement>();
            this.tblElements1 = new HashSet<tblElement>();
        }
    
        public int ID { get; set; }
        public string Connection_Name { get; set; }
        public string Server_Name { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Port_Number { get; set; }
        public string Default_Path { get; set; }
        public string FTP_Mode { get; set; }
        public string Database_Name { get; set; }
        public string Data_Connector_Connection_Type { get; set; }
        public string Gateway_Type { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public bool Is_Active { get; set; }
    
        public virtual ICollection<tblElement> tblElements { get; set; }
        public virtual ICollection<tblElement> tblElements1 { get; set; }
    }
}
