//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChart_Gauge_Range_Color
    {
        public int Id { get; set; }
        public int From_Value { get; set; }
        public int To_Value { get; set; }
        public string Color_Code { get; set; }
        public int Chart_Gauge_Id { get; set; }
    
        public virtual tblChart_Gauge tblChart_Gauge { get; set; }
    }
}
