//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChart_Gauge
    {
        public tblChart_Gauge()
        {
            this.tblChart_Gauge_Range_Color = new HashSet<tblChart_Gauge_Range_Color>();
        }
    
        public int Id { get; set; }
        public int Metric_Id { get; set; }
        public int Target_Matric_Id { get; set; }
        public int Minor_Unit { get; set; }
        public int Start_Angle { get; set; }
        public int End_Angle { get; set; }
        public int Min { get; set; }
        public int Max { get; set; }
        public string Metric_Label { get; set; }
        public string Target_Matric_Label { get; set; }
        public int DashboardWidget_Id { get; set; }
        public string Time_Line { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public bool Is_Deleted { get; set; }
        public short Precision { get; set; }
    
        public virtual ICollection<tblChart_Gauge_Range_Color> tblChart_Gauge_Range_Color { get; set; }
        public virtual tblDashboard_Widget tblDashboard_Widget { get; set; }
        public virtual tblMetric tblMetric { get; set; }
        public virtual tblMetric tblMetric1 { get; set; }
    }
}
