//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContainer
    {
        public tblContainer()
        {
            this.tblTags = new HashSet<tblTag>();
        }
    
        public int Id { get; set; }
        public string Container_Name { get; set; }
    
        public virtual ICollection<tblTag> tblTags { get; set; }
    }
}
