//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChart_Donut
    {
        public tblChart_Donut()
        {
            this.tblChart_Metric = new HashSet<tblChart_Metric>();
        }
    
        public int Id { get; set; }
        public string Chart_Title { get; set; }
        public string Time_Line { get; set; }
        public int DashboardWidget_Id { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public bool Is_Deleted { get; set; }
        public short Precision { get; set; }
    
        public virtual tblDashboard_Widget tblDashboard_Widget { get; set; }
        public virtual ICollection<tblChart_Metric> tblChart_Metric { get; set; }
    }
}
