//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashboard
    {
        public tblDashboard()
        {
            this.tblDashboard_Widget = new HashSet<tblDashboard_Widget>();
            this.tblDashboard1 = new HashSet<tblDashboard>();
            this.AspNetUserDashboards = new HashSet<AspNetUserDashboard>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Accessibility { get; set; }
        public bool Is_Deleted { get; set; }
        public int Layout_Option { get; set; }
        public string Widget_Positions { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public string Dashboard_Type { get; set; }
    
        public virtual ICollection<tblDashboard_Widget> tblDashboard_Widget { get; set; }
        public virtual ICollection<tblDashboard> tblDashboard1 { get; set; }
        public virtual tblDashboard tblDashboard2 { get; set; }
        public virtual ICollection<AspNetUserDashboard> AspNetUserDashboards { get; set; }
    }
}
