//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatabaseLog
    {
        public long ID { get; set; }
        public long User_ID { get; set; }
        public string Table_Name { get; set; }
        public long Row_ID { get; set; }
        public string Description { get; set; }
        public string Message { get; set; }
        public string Log_Level { get; set; }
        public System.DateTime Log_Date { get; set; }
    }
}
