//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElement
    {
        public tblElement()
        {
            this.tblElement1 = new HashSet<tblElement>();
            this.tblTagElements = new HashSet<tblTagElement>();
            this.tblElement_Extension = new HashSet<tblElement_Extension>();
            this.AspNetUserElements = new HashSet<AspNetUserElement>();
        }
    
        public long ID { get; set; }
        public string Element_Name { get; set; }
        public string Source_Element_Name_Live { get; set; }
        public string Source_Element_Name_History { get; set; }
        public Nullable<int> Connector_Live_ID { get; set; }
        public Nullable<int> Connector_History_ID { get; set; }
        public bool Is_Disabled { get; set; }
        public Nullable<long> Parent_Element_ID { get; set; }
        public Nullable<long> ExternalID { get; set; }
        public string Element_Tag_Type { get; set; }
        public Nullable<int> Unit_ID { get; set; }
        public Nullable<long> Freq { get; set; }
        public string Freq_Unit { get; set; }
        public Nullable<long> Recorded_Freq { get; set; }
        public string Recorded_Freq_Unit { get; set; }
        public Nullable<double> Min_Value { get; set; }
        public Nullable<double> Max_Value { get; set; }
        public string Data_Type { get; set; }
        public string Value_Type { get; set; }
        public bool IsRead_Only { get; set; }
    
        public virtual tblConnector tblConnector { get; set; }
        public virtual tblConnector tblConnector1 { get; set; }
        public virtual ICollection<tblElement> tblElement1 { get; set; }
        public virtual tblElement tblElement2 { get; set; }
        public virtual tblUnit tblUnit { get; set; }
        public virtual ICollection<tblTagElement> tblTagElements { get; set; }
        public virtual ICollection<tblElement_Extension> tblElement_Extension { get; set; }
        public virtual ICollection<AspNetUserElement> AspNetUserElements { get; set; }
    }
}
