//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHomePage_Widget
    {
        public int Widget_Id { get; set; }
        public string User_Id { get; set; }
        public int widget_x { get; set; }
        public int widget_y { get; set; }
        public int widget_width { get; set; }
        public int widget_height { get; set; }
    
        public virtual tblDashboard_Widget tblDashboard_Widget { get; set; }
    }
}
