//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLanguage
    {
        public tblLanguage()
        {
            this.tblLanguageDescriptions = new HashSet<tblLanguageDescription>();
        }
    
        public int ID { get; set; }
        public string Language_Name { get; set; }
        public string Culture_Value { get; set; }
        public bool Is_Disabled { get; set; }
    
        public virtual ICollection<tblLanguageDescription> tblLanguageDescriptions { get; set; }
    }
}
