//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLanguageDescription
    {
        public long ID { get; set; }
        public long Description_ID { get; set; }
        public int Language_ID { get; set; }
        public string Short_Desription { get; set; }
        public string Long_Description { get; set; }
    
        public virtual tblDescription tblDescription { get; set; }
        public virtual tblLanguage tblLanguage { get; set; }
    }
}
