//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatric
    {
        public int Id { get; set; }
        public string Matric_Name { get; set; }
        public string Rollup_Function { get; set; }
        public string Source { get; set; }
        public Nullable<int> Group_By { get; set; }
        public Nullable<int> Filter_By { get; set; }
        public Nullable<int> Filter_By_Option { get; set; }
        public string Filter_Text { get; set; }
    }
}
