//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTagElement
    {
        public long ID { get; set; }
        public long Tag_ID { get; set; }
        public long Element_ID { get; set; }
        public string Value { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual tblTag tblTag { get; set; }
        public virtual tblElement tblElement { get; set; }
    }
}
