//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTag_Type_Mapping
    {
        public string Tag_Type { get; set; }
        public string Point_Dim_Mapping { get; set; }
        public bool Is_Deleted { get; set; }
    }
}
