//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTag
    {
        public tblTag()
        {
            this.tblTags1 = new HashSet<tblTag>();
            this.tblTagElements = new HashSet<tblTagElement>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Description_ID { get; set; }
        public string Tag_Kind { get; set; }
        public string Tag_Type { get; set; }
        public string Tag_Value { get; set; }
        public Nullable<long> Parent_Tag_ID { get; set; }
        public bool Is_Disabled { get; set; }
        public Nullable<int> Container_ID { get; set; }
    
        public virtual tblContainer tblContainer { get; set; }
        public virtual tblDescription tblDescription { get; set; }
        public virtual ICollection<tblTag> tblTags1 { get; set; }
        public virtual tblTag tblTag1 { get; set; }
        public virtual ICollection<tblTagElement> tblTagElements { get; set; }
    }
}
