//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnonAnalytics.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnit
    {
        public tblUnit()
        {
            this.tblElements = new HashSet<tblElement>();
            this.tblMetrics = new HashSet<tblMetric>();
        }
    
        public int ID { get; set; }
        public string UName { get; set; }
        public string USymbol { get; set; }
        public bool Is_Disabled { get; set; }
    
        public virtual ICollection<tblElement> tblElements { get; set; }
        public virtual ICollection<tblMetric> tblMetrics { get; set; }
    }
}
